name: Publish on Release

on:
  release:
    types: [published]

# Use color in output
env:
  FORCE_COLOR: 3
  REACT_APP_GIT_SHA: ${{ github.sha }}
  REACT_APP_GIT_REF: ${{ github.ref }}
  REACT_APP_UPDATED_AT: ${{ github.event.repository.updated_at}}
  REACT_APP_PUBLISHED_AT: ${{ github.event.release.published_at }}
  REACT_APP_TAG_NAME: ${{ github.event.release.tag_name }}
  GENERATE_SOURCEMAP: false

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: npm
          registry-url: "https://registry.npmjs.org"
      - name: Install packages
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PETELE_PACKTRAK }}'
          channelId: live
          projectId: petele-packtrak
